
CREATE DATABASE airlineprofile
  WITH OWNER = postgres
       ENCODING = 'UTF8'
       TABLESPACE = pg_default
       LC_COLLATE = 'en_IN'
       LC_CTYPE = 'en_IN'
       CONNECTION LIMIT = -1;
    
SET AUTOCOMMIT = OFF;
   
CREATE TABLE AIRLINE (
	 CODE  varchar(10) NOT NULL,
	 CONSTRAINT PK_CONFIGURATIONS_CODE PRIMARY KEY (CODE)
);

CREATE TABLE SECTORS (
	 ID SERIAL NOT NULL,
	 DEPT varchar(10),
	 DEPT_COUNTRY varchar(10),
	 ARRV varchar(10),
	 ARRV_COUNTRY VARCHAR(10),
	 AIRLINE_CODE VARCHAR(10),
	 PRIMARY KEY (ID),
	 FOREIGN KEY (AIRLINE_CODE) REFERENCES AIRLINE (CODE)
);


